# Generated by Django 4.1.1 on 2022-09-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Name")),
                (
                    "description",
                    models.TextField(max_length=1028, verbose_name="Description"),
                ),
                ("country", models.CharField(max_length=128, verbose_name="Country")),
                ("city", models.CharField(max_length=128, verbose_name="City")),
            ],
        ),
    ]
