# Generated by Django 4.1.1 on 2022-09-28 08:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organisations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="org_members",
            field=models.ManyToManyField(
                related_name="org_members", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
